### ISSUE TITLE
Aprender básicos de vim

### ISSUE THREAD

**Issue by splucs** [splucs/ITAbots#4]
Quando se trabalha com git, comumente é necessário fazer alterações usando vim.

Deve-se aprender como salvar e sair do vim, assim como navegação básica.

**Material**
https://stackoverflow.com/questions/11828270/how-do-i-exit-the-vim-editor
https://www.openvim.com/tutorial.html

**Comment by knuppu** [comment]
Finalizado. O comando vimtutor foi interessante.
