### ISSUE TITLE
Aprender básicos de networking

### ISSUE THREAD

**Issue by splucs** [splucs/ITAbots#7]
Será necessário ter um conhecimento básico de networking para poder montar e configurar o cliente para o bot.
A melhor forma de aprender é Google, pesquise até conseguir responder todas as perguntas abaixo.

**Modelo OSI**
https://en.wikipedia.org/wiki/OSI_model.
- O que é a _physical layer_;
- O que é a _data link layer_;
  - O que é um endereço MAC;
- O que é a _network layer_;
  - O que é um endereço de IP
  - O que é um roteador
  - O que é um gateway
- O que é a _transport layer_;
  - O que é TCP/IP;
  - O que é UDP;
  - Qual a diferença entre TCP/IP e UDP;
  - O que é uma porta.
- O que é a _session layer_;
- O que é a _presentation layer_;
- O que é a _application layer_;
  - O que é o protocolo HTTP;
    - O que é uma GET request;
    - O que é uma POST request;
    - O que é uma PUT request;
  - O que é o protocolo HTTPS;
  - O que é o protocolo SSH;

**DNS**
- O que é DNS;
- O que é um provedor de DNS;
- Como funciona o processo de resolução de DNS.

**Comment by knuppu** [comment]
Finalizado.
